<?php

namespace Magyp\RendicionDeCajaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LiquidacionDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeyendaRepository extends EntityRepository
{
    
    public function Todas(){
	    $qb = $this->createQueryBuilder('ley')
			    ->select('ley')                
			    ->where("ley.borrado = 0")				
			    ;

	    return $qb->getQuery()->getResult();
	    ;
	}

    public function borradas(){
	    $qb = $this->createQueryBuilder('ley')
			    ->select('ley')                
			    ->where("ley.borrado = 1")				
			    ;

	    return $qb->getQuery()->getResult();
	    ;
	}
}
