<?php

namespace Magyp\RendicionDeCajaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LiquidacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiquidacionRepository extends EntityRepository
{
        public function borradas($idrendicion){
	    $qb = $this->createQueryBuilder('liq')
			    ->select('liq')                
			    ->where("liq.borrado = 1")	
				->andWhere("liq.rendicion = :idrendicion")
			    ->setParameter("idrendicion", $idrendicion)
			    ;

	    return $qb->getQuery()->getResult();
	    ;
	}
        public function BuscarPorRendicion($idrendicion){
	    $qb = $this->createQueryBuilder('liq')
			    ->select('liq')                
			    ->where("liq.borrado = 0")
			    ->andWhere("liq.rendicion = :idrendicion")
			    ->setParameter("idrendicion", $idrendicion)
			    ;

	    return $qb->getQuery()->getResult();
	    ;
	}
}
