<?php

namespace Magyp\RendicionDeCajaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LiquidacionDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiquidacionDetalleRepository extends EntityRepository
{
    
    public function buscarDetallesDeLiquidacion($idLiquidacion){
		$qb = $this->createQueryBuilder('det')
				->select('det', 'imp')
                ->join("det.imputacion", "imp")
				->where("det.liquidacion = :id")
				->setParameter("id", $idLiquidacion)
                ->orderBy('det.programa, imp.codigo','ASC')
				;
		return $qb->getQuery()->getResult();
		;
	}
}