<?php

namespace Magyp\RendicionDeCajaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends EntityRepository
{
	public function ultimaSession($usuario,$sessionidActual){
		
		$qb = $this->createQueryBuilder('sess')
				//->select('sess','max(sess.fechalogueo)')
				->select('sess')
				->where("sess.usuario = :id")
				->setParameter("id", $usuario->getId())
				->andWhere("sess.sessionid <> :sessionid")
				->setParameter("sessionid", $sessionidActual)
				//->groupBy("sess.usuario")
				->orderBy("sess.fechalogueo","DESC")
				->setMaxResults(1);
				//->andWhere("");
		return $qb->getQuery()->getResult();
		;
	}	
}
